from app import db

class Transportation(db.Model):
    id = db.Column(db.Integer, primary_key=True,nullable=False)
    stop_id = db.Column(db.Integer,nullable=False)
    on_street = db.Column(db.String(128))
    cross_street = db.Column(db.String(128))
    routes = db.Column(db.String(60))
    boardings = db.Column(db.Float)
    alightings = db.Column(db.Float)
    month_beginning = db.Column(db.String(60)) 
    daytype = db.Column(db.String(60))
    location = db.Column(db.String(128)) 

class TransformedData(db.Model):
    id = db.Column(db.Integer, primary_key=True,nullable=False)
    stop_id = db.Column(db.Integer,nullable=False)
    on_street = db.Column(db.String(128))
    cross_street = db.Column(db.String(128))
    routes = db.Column(db.String(60))
    boardings = db.Column(db.Float)
    alightings = db.Column(db.Float)
    month_beginning = db.Column(db.String(60)) 
    daytype = db.Column(db.String(60))
    location = db.Column(db.String(128)) 
    lat = db.Column(db.Float)
    lon = db.Column(db.Float)
    num_routes = db.Column(db.Float)
    route = db.Column(db.String(60))
    total_traffic = db.Column(db.Float)
